name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@5c6c06aa0e3d7a6a9b6cba05c078c51631b5f11a # v39.1.1
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.PAT }}
