name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@a1ed1d0adddfdf138192d1fbe3150a80094dee6a # v40.3.1
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.PAT }}
